
# SRC_DIR = ../../src
# SRC = $(shell find $(SRC_DIR) -name '*.cpp')
# SRCLEXER = $(shell find ../../lib/GenericLexer -name '*.cpp')

all:
	@g++ -Wall -Wno-write-strings -g -fPIC -shared -I../../include -I../../lib/GenericLexer/include os.h os.cpp -o plugatestplugin.so